<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.11.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.11.1" />
    <PackageReference Include="nac.Logging" Version="1.0.3" />
  </ItemGroup>
  
  
  <ItemGroup>
    <ProjectReference Include="..\nac.wpf.forms\nac.wpf.forms.csproj" />
  </ItemGroup>
</Project>